"""
الخريطة الكاملة: كل صفحة → البنود اللي فيها فقط
مبنية بالظبط على ملف equations_and_pages_detections.txt
"""

DRAWING_ITEMS_MAP = {

    # ══════════════════════════════════════════════
    # STRUCTURAL DRAWINGS
    # ══════════════════════════════════════════════

    "foundations": {
        "label_en": "Foundations",
        "label_ar": "الأساسات",
        "pdf_type": "structural",
        "items": [
            {
                "key":           "excavation",
                "name_en":       "Excavation",
                "name_ar":       "الحفر",
                "unit":          "m³",
                "formula_str":   "(longest_length + 2) × (longest_width + 2) × 1.25",
                "inputs_needed": ["longest_length", "longest_width"],
                "ai_question":   "What is the longest length and longest width of the building footprint in meters?",
            },
            {
                "key":           "foundation_pcc",
                "name_en":       "Foundation PCC (Blinding)",
                "name_ar":       "بيتون عادي الأساسات",
                "unit":          "m³",
                "formula_str":   "(length + 0.20) × (width + 0.20) × 0.10 × count",
                "inputs_needed": ["foundations_schedule"],
                "ai_question":   "List all footing types with their length (m), width (m), and count.",
            },
            {
                "key":           "foundation_concrete",
                "name_en":       "Foundation Concrete",
                "name_ar":       "خرسانة الأساسات",
                "unit":          "m³",
                "formula_str":   "width × length × depth × count",
                "inputs_needed": ["foundations_schedule"],
                "ai_question":   "List all footing types with length (m), width (m), depth (m), and count.",
            },
            {
                "key":           "foundation_bitumen",
                "name_en":       "Foundation Bitumen",
                "name_ar":       "بيتومين الأساسات",
                "unit":          "m²",
                "formula_str":   "(area + perimeter × depth) × count",
                "inputs_needed": ["foundations_schedule"],
                "ai_question":   "List all footing types with length (m), width (m), depth (m), and count.",
            },
            {
                "key":           "neck_column_concrete",
                "name_en":       "Neck Column Concrete",
                "name_ar":       "خرسانة أعمدة الرقبة",
                "unit":          "m³",
                "formula_str":   "width × length × 1.0 × count",
                "inputs_needed": ["neck_columns_schedule"],
                "ai_question":   "List all neck column types (between footing and tie beam) with width (m), length (m), and count.",
            },
            {
                "key":           "neck_column_bitumen",
                "name_en":       "Neck Column Bitumen",
                "name_ar":       "بيتومين أعمدة الرقبة",
                "unit":          "m²",
                "formula_str":   "2 × (length + width) × 1.0 × count",
                "inputs_needed": ["neck_columns_schedule"],
                "ai_question":   "List all neck column types with width (m), length (m), and count.",
            },
            {
                "key":           "anti_termite_found",
                "name_en":       "Anti-Termite (Foundations)",
                "name_ar":       "مبيد حشرات الأساسات",
                "unit":          "m²",
                "formula_str":   "longest_length × longest_width",
                "inputs_needed": ["longest_length", "longest_width"],
                "ai_question":   "What is the overall building footprint longest length and width in meters?",
            },
            {
                "key":           "polyethylene_found",
                "name_en":       "Polyethylene Sheet (Foundations)",
                "name_ar":       "نايلون الأساسات",
                "unit":          "m²",
                "formula_str":   "Total PCC Volume ÷ 0.10",
                "inputs_needed": ["foundations_schedule"],
                "ai_question":   "List all footing types with length (m), width (m), and count (for PCC area calculation).",
            },
            {
                "key":           "road_base",
                "name_en":       "Road Base (Sub-Grade Fill)",
                "name_ar":       "الرمل المدموك",
                "unit":          "m³",
                "formula_str":   "longest_length × longest_width × 0.25",
                "inputs_needed": ["longest_length", "longest_width"],
                "ai_question":   "What is the overall building footprint longest length and width in meters?",
            },
            {
                "key":           "backfill",
                "name_en":       "Backfill",
                "name_ar":       "الردم",
                "unit":          "m³",
                "formula_str":   "(exc_area × (exc_depth + 0.15)) - total_concrete",
                "inputs_needed": ["longest_length", "longest_width", "foundations_schedule"],
                "ai_question":   "What is the overall footprint length and width? List all footing dimensions for concrete volume calculation.",
            },
        ],
    },

    "tie_beam": {
        "label_en": "Tie Beam",
        "label_ar": "الميدة",
        "pdf_type": "structural",
        "items": [
            {
                "key":           "tie_beam_concrete",
                "name_en":       "Tie Beam Concrete",
                "name_ar":       "خرسانة الميدة",
                "unit":          "m³",
                "formula_str":   "width × depth × total_length",
                "inputs_needed": ["tb_width", "tb_depth", "tb_total_length"],
                "ai_question":   "What is the tie beam width (m), depth (m), and total length (m)?",
            },
            {
                "key":           "tie_beam_pcc",
                "name_en":       "Tie Beam PCC (Blinding)",
                "name_ar":       "بيتون عادي الميدة",
                "unit":          "m³",
                "formula_str":   "(width + 0.20) × 0.10 × total_length",
                "inputs_needed": ["tb_width", "tb_total_length"],
                "ai_question":   "What is the tie beam width (m) and total length (m)?",
            },
            {
                "key":           "tie_beam_bitumen",
                "name_en":       "Tie Beam Bitumen",
                "name_ar":       "بيتومين الميدة",
                "unit":          "m²",
                "formula_str":   "total_length × depth × 2",
                "inputs_needed": ["tb_total_length", "tb_depth"],
                "ai_question":   "What is the tie beam total length (m) and depth (m)?",
            },
            {
                "key":           "slab_on_grade",
                "name_en":       "Slab on Grade Concrete",
                "name_ar":       "خرسانة بلاطة الأرضية",
                "unit":          "m³",
                "formula_str":   "gf_area × 1.1 × 0.10",
                "inputs_needed": ["gf_area"],
                "ai_question":   "What is the total ground floor area (m²)?",
            },
            {
                "key":           "solid_block_work",
                "name_en":       "Solid Block Work (Sub-Grade)",
                "name_ar":       "بلوك مصمت تحت الأرض",
                "unit":          "m³",
                "formula_str":   "external_perimeter × 0.9 × 1.0",
                "inputs_needed": ["external_perimeter"],
                "ai_question":   "What is the external perimeter of the building (m)?",
            },
            {
                "key":           "block_work_bitumen",
                "name_en":       "Block Work Bitumen",
                "name_ar":       "بيتومين البلوك",
                "unit":          "m²",
                "formula_str":   "external_perimeter × 1.0 × 2",
                "inputs_needed": ["external_perimeter"],
                "ai_question":   "What is the external perimeter of the building (m)?",
            },
            {
                "key":           "anti_termite_tb",
                "name_en":       "Anti-Termite (Tie Beam)",
                "name_ar":       "مبيد حشرات الميدة",
                "unit":          "m²",
                "formula_str":   "gf_area × 1.1",
                "inputs_needed": ["gf_area"],
                "ai_question":   "What is the total ground floor area (m²)?",
            },
            {
                "key":           "poly_sheet_tb",
                "name_en":       "Polyethylene Sheet (Tie Beam)",
                "name_ar":       "نايلون الميدة",
                "unit":          "m²",
                "formula_str":   "SOG_area + PCC_area",
                "inputs_needed": ["gf_area", "tb_width", "tb_total_length"],
                "ai_question":   "What is the ground floor area (m²), tie beam width (m), and total tie beam length (m)?",
            },
        ],
    },

    "upper_columns": {
        "label_en": "Columns (All Floors)",
        "label_ar": "الأعمدة",
        "pdf_type": "structural",
        "items": [
            {
                "key":           "col_gf_to_1st",
                "name_en":       "Column Concrete (GF → 1st Floor)",
                "name_ar":       "خرسانة أعمدة الأرضي",
                "unit":          "m³",
                "formula_str":   "length × width × 4.0 × count",
                "inputs_needed": ["columns_schedule_gf"],
                "ai_question":   "List all column types for ground floor with length (m), width (m), and count.",
            },
            {
                "key":           "col_1st_to_2nd",
                "name_en":       "Column Concrete (1st → 2nd Floor)",
                "name_ar":       "خرسانة أعمدة الأول",
                "unit":          "m³",
                "formula_str":   "length × width × 4.0 × count",
                "inputs_needed": ["columns_schedule_1f"],
                "ai_question":   "List all column types for 1st floor with length (m), width (m), and count.",
            },
            {
                "key":           "col_roof",
                "name_en":       "Column Concrete (Roof)",
                "name_ar":       "خرسانة أعمدة السطح",
                "unit":          "m³",
                "formula_str":   "length × width × 3.5 × count",
                "inputs_needed": ["columns_schedule_roof"],
                "ai_question":   "List all column types for roof level with length (m), width (m), and count.",
            },
        ],
    },

    "slab_1st": {
        "label_en": "1st Floor Slab",
        "label_ar": "بلاطة الدور الأول",
        "pdf_type": "structural",
        "items": [
            {
                "key":           "beam_concrete_1st",
                "name_en":       "Beam Concrete (1st Floor)",
                "name_ar":       "خرسانة كمرات الأول",
                "unit":          "m³",
                "formula_str":   "length × width × depth (per beam)",
                "inputs_needed": ["beams_schedule_1f"],
                "ai_question":   "List all beam types for 1st floor slab with length (m), width (m), and depth (m).",
            },
            {
                "key":           "slab_concrete_1st",
                "name_en":       "Slab Concrete (1st Floor)",
                "name_ar":       "خرسانة بلاطة الأول",
                "unit":          "m³",
                "formula_str":   "area × thickness",
                "inputs_needed": ["slab_area_1f", "slab_thickness_1f"],
                "ai_question":   "What is the 1st floor slab area (m²) and thickness (m)?",
            },
        ],
    },

    "slab_2nd": {
        "label_en": "2nd Floor Slab",
        "label_ar": "بلاطة الدور الثاني",
        "pdf_type": "structural",
        "items": [
            {
                "key":           "beam_concrete_2nd",
                "name_en":       "Beam Concrete (2nd Floor)",
                "name_ar":       "خرسانة كمرات الثاني",
                "unit":          "m³",
                "formula_str":   "length × width × depth (per beam)",
                "inputs_needed": ["beams_schedule_2f"],
                "ai_question":   "List all beam types for 2nd floor slab with length (m), width (m), depth (m).",
            },
            {
                "key":           "slab_concrete_2nd",
                "name_en":       "Slab Concrete (2nd Floor)",
                "name_ar":       "خرسانة بلاطة الثاني",
                "unit":          "m³",
                "formula_str":   "area × thickness",
                "inputs_needed": ["slab_area_2f", "slab_thickness_2f"],
                "ai_question":   "What is the 2nd floor slab area (m²) and thickness (m)?",
            },
        ],
    },

    "roof_slab": {
        "label_en": "Roof Slab",
        "label_ar": "بلاطة السطح",
        "pdf_type": "structural",
        "items": [
            {
                "key":           "slab_concrete_roof",
                "name_en":       "Slab Concrete (Roof)",
                "name_ar":       "خرسانة بلاطة السطح",
                "unit":          "m³",
                "formula_str":   "area × thickness",
                "inputs_needed": ["slab_area_roof", "slab_thickness_roof"],
                "ai_question":   "What is the roof slab area (m²) and thickness (m)?",
            },
            {
                "key":           "beam_concrete_roof",
                "name_en":       "Beam Concrete (Roof)",
                "name_ar":       "خرسانة كمرات السطح",
                "unit":          "m³",
                "formula_str":   "length × width × depth (per beam)",
                "inputs_needed": ["beams_schedule_roof"],
                "ai_question":   "List all roof beam types with length (m), width (m), depth (m).",
            },
            {
                "key":           "parapet_block_work",
                "name_en":       "Parapet Block Work",
                "name_ar":       "بلوك الباربيت",
                "unit":          "m²",
                "formula_str":   "perimeter × 1.0",
                "inputs_needed": ["roof_perimeter"],
                "ai_question":   "What is the roof slab perimeter (m)?",
            },
            {
                "key":           "parapet_concrete",
                "name_en":       "Parapet Concrete Coping",
                "name_ar":       "كمرة الباربيت",
                "unit":          "m³",
                "formula_str":   "perimeter × 0.20 × 0.20",
                "inputs_needed": ["roof_perimeter"],
                "ai_question":   "What is the roof slab perimeter (m)?",
            },
            {
                "key":           "staircase_1st",
                "name_en":       "Staircase Concrete",
                "name_ar":       "خرسانة السلم",
                "unit":          "m³",
                "formula_str":   "volume per level × (levels − 1)",
                "inputs_needed": ["structural_levels"],
                "ai_question":   "How many structural floors does the villa have?",
            },
        ],
    },

    # ══════════════════════════════════════════════
    # ARCHITECTURAL DRAWINGS
    # ══════════════════════════════════════════════

    "ground_floor_plan": {
        "label_en": "Ground Floor Plan",
        "label_ar": "مسقط الدور الأرضي",
        "pdf_type": "architectural",
        "items": [
            {"key": "thermal_block_gf", "name_en": "Thermal Block External (GF) (200mm Thickness)",  "name_ar": "بلوك حراري خارجي أرضي (سماكة 200mm)",  "unit": "m²", "formula_str": "ext_perimeter × floor_height",          "inputs_needed": ["ext_perimeter", "gf_height"],                            "ai_question": "What is the external perimeter (m) and floor-to-ceiling height (m) of the ground floor?"},
            {"key": "internal_block_gf","name_en": "Internal Block Work (GF) (200mm Thickness)",     "name_ar": "بلوك داخلي أرضي (سماكة 200mm)",         "unit": "m²", "formula_str": "int_walls_length × floor_height",      "inputs_needed": ["int_walls_length_gf", "gf_height"],                      "ai_question": "What is the total internal walls length (m) for the ground floor? Include all partition walls."},
            {"key": "internal_block_10_gf","name_en": "Internal Block Work (GF) (100mm Thickness)",     "name_ar": "بلوك داخلي أرضي (سماكة 100mm)",         "unit": "m²", "formula_str": "int_walls_10cm × floor_height",      "inputs_needed": ["int_walls_length_gf", "gf_height"],                      "ai_question": "What is the total internal walls length (m) for the ground floor? Include all partition walls."},
            {"key": "dry_floor_gf",     "name_en": "Dry Area Flooring (GF)",       "name_ar": "بلاط الأرضي الجاف",       "unit": "m²", "formula_str": "total_area - wet_area",                "inputs_needed": ["gf_total_area", "gf_wet_area"],                          "ai_question": "What is the total ground floor area (m²) and total wet area (bathrooms + kitchen + laundry) (m²)?"},
            {"key": "wet_floor_gf",     "name_en": "Wet Area Flooring (GF)",       "name_ar": "بلاط الأرضي الرطب",       "unit": "m²", "formula_str": "sum of toilets + bathrooms + kitchens", "inputs_needed": ["gf_wet_area"],                                           "ai_question": "List all wet rooms (bathrooms, toilets, kitchen, laundry) with their individual areas (m²)."},
            {"key": "wall_tiles_gf",    "name_en": "Wall Tiles (GF Wet Areas)",    "name_ar": "بلاط جدران رطب أرضي",    "unit": "m²", "formula_str": "wet_perimeter × (height - 0.50)",      "inputs_needed": ["gf_wet_perimeter", "gf_height"],                         "ai_question": "What is the total perimeter of all wet rooms (m) and floor height (m)?"},
            {"key": "skirting_gf",      "name_en": "Skirting (GF)",                "name_ar": "قرنيش أرضي الأرضي",       "unit": "m",  "formula_str": "dry_area_perimeter",                   "inputs_needed": ["gf_dry_perimeter"],                                      "ai_question": "What is the total perimeter of dry areas (m) for the ground floor?"},
            {"key": "int_paint_gf",     "name_en": "Internal Paint (GF)",          "name_ar": "دهان داخلي أرضي",         "unit": "m²", "formula_str": "skirting_length × floor_height",         "inputs_needed": ["gf_dry_perimeter", "gf_height"],                         "ai_question": "What is the dry area perimeter (m) and floor height (m)?"},
            {"key": "int_plaster_gf",   "name_en": "Internal Plaster (GF)",        "name_ar": "لياسة داخلية أرضي",       "unit": "m²", "formula_str": "(int_block × 2) + ext_block",            "inputs_needed": ["int_walls_length_gf", "ext_perimeter", "gf_height"],     "ai_question": "What is internal walls total length (m), external perimeter (m), and floor height (m)?"},
            {"key": "dry_ceiling_gf",   "name_en": "Dry Area Ceiling (GF)",        "name_ar": "أسقف جافة أرضي",          "unit": "m²", "formula_str": "dry_area_flooring",                     "inputs_needed": ["gf_total_area", "gf_wet_area"],                          "ai_question": "What is total floor area (m²) and wet area (m²)?"},
            {"key": "wet_ceiling_gf",   "name_en": "Wet Area Ceiling (GF)",        "name_ar": "أسقف رطبة أرضي",          "unit": "m²", "formula_str": "wet_area_flooring",                     "inputs_needed": ["gf_wet_area"],                                           "ai_question": "What is the total wet area (m²) for the ground floor?"},
        ],
    },

    "first_floor_plan": {
        "label_en": "1st Floor Plan",
        "label_ar": "مسقط الدور الأول",
        "pdf_type": "architectural",
        "items": [
            {"key": "thermal_block_1f",  "name_en": "Thermal Block External (1F) (200mm Thickness)", "name_ar": "بلوك حراري خارجي أول (سماكة 200mm)",   "unit": "m²", "formula_str": "ext_perimeter × floor_height",     "inputs_needed": ["ext_perimeter", "f1_height"],                              "ai_question": "External perimeter (m) and floor height (m) of 1st floor?"},
            {"key": "internal_block_1f", "name_en": "Internal Block Work (1F) (200mm Thickness)",    "name_ar": "بلوك داخلي أول (سماكة 200mm)",          "unit": "m²", "formula_str": "int_walls_length × floor_height", "inputs_needed": ["int_walls_length_1f", "f1_height"],                        "ai_question": "Total internal walls length (m) for 1st floor?"},
            {"key": "internal_block_10_1f", "name_en": "Internal Block Work (1F) (100mm Thickness)",    "name_ar": "بلوك داخلي أول (سماكة 100mm)",          "unit": "m²", "formula_str": "int_walls_10cm × floor_height", "inputs_needed": ["int_walls_length_1f", "f1_height"],                        "ai_question": "Total internal walls length (m) for 1st floor?"},
            {"key": "dry_floor_1f",      "name_en": "Dry Area Flooring (1F)",      "name_ar": "بلاط الأول الجاف",        "unit": "m²", "formula_str": "total_area - wet_area",           "inputs_needed": ["f1_total_area", "f1_wet_area"],                            "ai_question": "Total 1st floor area (m²) and wet area (m²)?"},
            {"key": "wet_floor_1f",      "name_en": "Wet Area Flooring (1F)",      "name_ar": "بلاط الأول الرطب",        "unit": "m²", "formula_str": "sum of wet rooms",                "inputs_needed": ["f1_wet_area"],                                             "ai_question": "List wet rooms on 1st floor with areas (m²)."},
            {"key": "wall_tiles_1f",     "name_en": "Wall Tiles (1F Wet Areas)",   "name_ar": "بلاط جدران رطب أول",     "unit": "m²", "formula_str": "wet_perimeter × (height - 0.50)", "inputs_needed": ["f1_wet_perimeter", "f1_height"],                           "ai_question": "Total wet rooms perimeter (m) and floor height (m) for 1st floor?"},
            {"key": "wet_wp_1f",         "name_en": "Wet Area Waterproofing (1F)", "name_ar": "عزل المناطق الرطبة أول", "unit": "m²", "formula_str": "wet_area (upper floors only)",    "inputs_needed": ["f1_wet_area"],                                             "ai_question": "Total wet area (m²) on 1st floor for waterproofing?"},
            {"key": "balcony_wp_1f",     "name_en": "Balcony Waterproofing (1F)", "name_ar": "عزل البلكونة أول",        "unit": "m²", "formula_str": "balcony_area",                    "inputs_needed": ["f1_balcony_area"],                                         "ai_question": "Total balcony area (m²) on 1st floor?"},
            {"key": "int_plaster_1f",    "name_en": "Internal Plaster (1F)",      "name_ar": "لياسة داخلية أول",         "unit": "m²", "formula_str": "(int_block × 2) + ext_block",     "inputs_needed": ["int_walls_length_1f", "ext_perimeter", "f1_height"],       "ai_question": "Internal walls length (m), external perimeter (m), floor height (m) for 1st floor?"},
            {"key": "int_paint_1f",      "name_en": "Internal Paint (1F)",        "name_ar": "دهان داخلي أول",           "unit": "m²", "formula_str": "dry_perimeter × floor_height",    "inputs_needed": ["f1_dry_perimeter", "f1_height"],                           "ai_question": "Dry area perimeter (m) and floor height (m) for 1st floor?"},
        ],
    },

    "second_floor_plan": {
        "label_en": "2nd Floor Plan",
        "label_ar": "مسقط الدور الثاني",
        "pdf_type": "architectural",
        "items": [
            {"key": "thermal_block_2f",  "name_en": "Thermal Block External (2F) (200mm Thickness)", "name_ar": "بلوك حراري خارجي ثاني (سماكة 200mm)", "unit": "m²", "formula_str": "ext_perimeter × floor_height",     "inputs_needed": ["ext_perimeter", "f2_height"],                              "ai_question": "External perimeter (m) and floor height (m) of 2nd floor?"},
            {"key": "internal_block_2f", "name_en": "Internal Block Work (2F) (200mm Thickness)",    "name_ar": "بلوك داخلي ثاني (سماكة 200mm)",        "unit": "m²", "formula_str": "int_walls_length × floor_height", "inputs_needed": ["int_walls_length_2f", "f2_height"],                        "ai_question": "Total internal walls length (m) for 2nd floor?"},
            {"key": "internal_block_10_2f", "name_en": "Internal Block Work (2F) (100mm Thickness)",    "name_ar": "بلوك داخلي ثاني (سماكة 100mm)",        "unit": "m²", "formula_str": "int_walls_10cm × floor_height", "inputs_needed": ["int_walls_length_2f", "f2_height"],                        "ai_question": "Total internal walls length (m) for 2nd floor?"},
            {"key": "dry_floor_2f",      "name_en": "Dry Area Flooring (2F)",      "name_ar": "بلاط الثاني الجاف",      "unit": "m²", "formula_str": "total_area - wet_area",           "inputs_needed": ["f2_total_area", "f2_wet_area"],                            "ai_question": "Total 2nd floor area (m²) and wet area (m²)?"},
            {"key": "wet_floor_2f",      "name_en": "Wet Area Flooring (2F)",      "name_ar": "بلاط الثاني الرطب",      "unit": "m²", "formula_str": "sum of wet rooms",                "inputs_needed": ["f2_wet_area"],                                             "ai_question": "List wet rooms on 2nd floor with areas (m²)."},
            {"key": "wet_wp_2f",         "name_en": "Wet Area Waterproofing (2F)", "name_ar": "عزل رطب ثاني",           "unit": "m²", "formula_str": "wet_area (upper floors)",          "inputs_needed": ["f2_wet_area"],                                             "ai_question": "Total wet area (m²) on 2nd floor?"},
            {"key": "wall_tiles_2f",     "name_en": "Wall Tiles (2F)",             "name_ar": "بلاط جدران رطب ثاني",   "unit": "m²", "formula_str": "wet_perimeter × (height - 0.50)", "inputs_needed": ["f2_wet_perimeter", "f2_height"],                           "ai_question": "Total wet rooms perimeter (m) and floor height (m) for 2nd floor?"},
            {"key": "int_plaster_2f",    "name_en": "Internal Plaster (2F)",      "name_ar": "لياسة داخلية ثاني",       "unit": "m²", "formula_str": "(int_block × 2) + ext_block",     "inputs_needed": ["int_walls_length_2f", "ext_perimeter", "f2_height"],       "ai_question": "Internal walls length (m), external perimeter (m), height (m) for 2nd floor?"},
        ],
    },

    "roof_floor_plan": {
        "label_en": "Roof Floor Plan",
        "label_ar": "مسقط السطح",
        "pdf_type": "architectural",
        "items": [
            {
                "key":           "roof_waterproofing",
                "name_en":       "Roof Waterproofing",
                "name_ar":       "عزل السطح",
                "unit":          "m²",
                "formula_str":   "roof_slab_area × 1.2",
                "inputs_needed": ["roof_slab_area"],
                "ai_question":   "What is the total roof slab area (m²)?",
            },
        ],
    },

    "elevations": {
        "label_en": "Elevations",
        "label_ar": "الواجهات",
        "pdf_type": "architectural",
        "items": [
            {
                "key":           "external_plaster",
                "name_en":       "External Plaster",
                "name_ar":       "لياسة خارجية",
                "unit":          "m²",
                "formula_str":   "ext_perimeter × (total_villa_height + 1.2)",
                "inputs_needed": ["ext_perimeter", "total_villa_height"],
                "ai_question":   "What is the total villa height (m) from ground to roof top? And external perimeter (m)?",
            },
            {
                "key":           "external_finishes",
                "name_en":       "External Finishes",
                "name_ar":       "تشطيب خارجي",
                "unit":          "m²",
                "formula_str":   "ext_perimeter × (total_villa_height + 1.2)",
                "inputs_needed": ["ext_perimeter", "total_villa_height"],
                "ai_question":   "What is the total villa height (m) and external perimeter (m)?",
            },
        ],
    },

    "setting_out": {
        "label_en": "Setting Out / Site Plan",
        "label_ar": "مخطط الموقع",
        "pdf_type": "architectural",
        "items": [
            {
                "key":           "interlock_paving",
                "name_en":       "Interlock Paving",
                "name_ar":       "رصف إنترلوك",
                "unit":          "m²",
                "formula_str":   "plot_area - gf_footprint_area",
                "inputs_needed": ["plot_area", "gf_area"],
                "ai_question":   "What is the total plot area (m²) and the ground floor building footprint area (m²)?",
            },
            {
                "key":           "compound_wall",
                "name_en":       "Compound Wall",
                "name_ar":       "سور الموقع",
                "unit":          "m",
                "formula_str":   "compound_perimeter_length",
                "inputs_needed": ["compound_length"],
                "ai_question":   "What is the total length of the compound/boundary wall (m)?",
            },
        ],
    },

    "schedules": {
        "label_en": "Door & Window Schedules",
        "label_ar": "جداول الأبواب والنوافذ",
        "pdf_type": "architectural",
        "items": [
            {
                "key":           "door_openings",
                "name_en":       "Door Openings",
                "name_ar":       "الأبواب",
                "unit":          "Nr",
                "formula_str":   "Total count of all doors",
                "inputs_needed": ["doors_schedule"],
                "ai_question":   "List all door types from the schedule with their count. Give total door count.",
            },
            {
                "key":           "window_openings",
                "name_en":       "Window Openings",
                "name_ar":       "النوافذ",
                "unit":          "m²",
                "formula_str":   "sum(length × width × count)",
                "inputs_needed": ["windows_schedule"],
                "ai_question":   "List all window types from the schedule with width (m), height (m), and count.",
            },
        ],
    },
}
