[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false

[theme]
base = "dark"
primaryColor = "#2563eb"
backgroundColor = "#020617"
secondaryBackgroundColor = "#0f172a"
textColor = "#f8fafc"
